name: Forex-Dynamics
favicon: null
layout_spectrum: 0.15333492122590542
typography_spectrum: 0.7738681556656957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8732490888796747
  lightness: 0.026031362591311336
  saturation: 0.6381595546845347
  rhythmicContrast: 0.9784195281099528
purpose: []
